# Generated by Django 4.2.9 on 2024-01-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='title',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='rank',
        ),
    ]
