# Generated by Django 4.2.9 on 2024-02-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_category_quizz_result_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='url',
        ),
    ]
