# Generated by Django 4.2.9 on 2024-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_remove_quizz_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Category'),
        ),
    ]
