# Generated by Django 4.2.9 on 2024-02-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_alter_player_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizz',
            new_name='Quiz',
        ),
    ]
