# Generated by Django 4.2.9 on 2024-02-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_rename_quizz_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct_answer',
            new_name='answer',
        ),
    ]
