# Generated by Django 4.2.9 on 2024-02-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_rename_correct_answer_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.answer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.quiz')),
            ],
        ),
    ]
