# Generated by Django 4.2.9 on 2024-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_questionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
