# Generated by Django 4.2.9 on 2024-02-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0011_alter_result_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.player')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.quiz')),
            ],
        ),
    ]
