# Generated by Django 4.2.9 on 2024-02-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0015_remove_questionresponse_quiz_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='active_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.quizattempt'),
        ),
    ]
