# Generated by Django 4.2.9 on 2024-02-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0016_remove_quizattempt_player_player_active_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='single choice', max_length=200),
        ),
    ]
