# Generated by Django 4.2.9 on 2024-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0017_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(default='Beginner', max_length=200),
        ),
    ]
