# Generated by Django 4.2.9 on 2024-02-12 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0018_alter_player_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='gui.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.question')),
            ],
        ),
    ]
