# Generated by Django 4.2.9 on 2024-02-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0019_multiplechoiceanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleChoiceAnswer',
        ),
    ]
