# Generated by Django 4.2.9 on 2024-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0020_delete_multiplechoiceanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single choice', 'Single Choice'), ('multiple choice', 'Multiple Choice')], default='single choice', max_length=15),
        ),
    ]
