# Generated by Django 4.2.9 on 2024-02-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0021_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers_at_end',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='fail_text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='random_order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='single_attempt',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='success_text',
        ),
    ]
