# Generated by Django 4.2.9 on 2024-02-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0023_forum_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
    ]
