# Generated by Django 4.2.9 on 2024-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0024_remove_forum_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category'),
        ),
    ]
