# Generated by Django 4.2.9 on 2024-02-14 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0025_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='player',
            field=models.ForeignKey(help_text='The player who created the quiz.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.player', verbose_name='Player'),
        ),
    ]
