# Generated by Django 4.2.9 on 2024-02-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0027_question_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.player'),
        ),
    ]
