# Generated by Django 4.2.9 on 2024-02-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0028_answer_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='question',
            name='player',
        ),
    ]
