# Generated by Django 4.2.9 on 2024-02-15 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0030_category_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='PointsPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.player')),
            ],
        ),
    ]
