# Generated by Django 4.2.9 on 2024-02-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0031_player_registration_date_pointsperday'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
