# Generated by Django 4.2.9 on 2024-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0032_category_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
