# Generated by Django 4.2.9 on 2024-02-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0033_forum_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='player_name',
        ),
        migrations.AddField(
            model_name='forum',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.player'),
        ),
    ]
