# Generated by Django 4.2.9 on 2024-02-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0034_remove_forum_player_name_forum_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPlayerSession',
            fields=[
                ('room_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ended', models.BooleanField(default=False)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='gui.player')),
                ('players', models.ManyToManyField(related_name='game_players', to='gui.player')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.quiz')),
            ],
        ),
    ]
