# Generated by Django 4.2.9 on 2024-02-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0035_multiplayersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayersession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.question'),
        ),
    ]
