# Generated by Django 4.2.9 on 2024-02-17 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gui', '0036_multiplayersession_current_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplayersession',
            name='creater',
        ),
        migrations.AddField(
            model_name='multiplayersession',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='gui.player', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='category',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.player', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.CharField(max_length=500, verbose_name='Discussion'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.forum', verbose_name='Forum'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=300, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='multiplayersession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.question', verbose_name='Current Question'),
        ),
        migrations.AlterField(
            model_name='multiplayersession',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Ended'),
        ),
        migrations.AlterField(
            model_name='multiplayersession',
            name='players',
            field=models.ManyToManyField(related_name='game_players', to='gui.player', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='multiplayersession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='multiplayersession',
            name='room_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Room Code'),
        ),
        migrations.AlterField(
            model_name='player',
            name='active_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.quizattempt', verbose_name='Active Attempt'),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(default='Beginner', max_length=200, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='pointsperday',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pointsperday',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='pointsperday',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single choice', 'Single Choice'), ('multiple choice', 'Multiple Choice')], default='single choice', max_length=15, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.answer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='responses',
            field=models.ManyToManyField(to='gui.questionresponse', verbose_name='Responses'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
