# Generated by Django 4.2.9 on 2025-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0037_remove_multiplayersession_creater_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplayersession',
            name='ended',
        ),
        migrations.AddField(
            model_name='multiplayersession',
            name='started',
            field=models.BooleanField(default=False, verbose_name='Started'),
        ),
    ]
