# Generated by Django 4.2.9 on 2025-04-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0038_remove_multiplayersession_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayersession',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
