# Generated by Django 5.0.1 on 2024-01-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_question_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoty_name',
            new_name='category_name',
        ),
    ]
