from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done_temp.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm_temp.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete_temp.html'), name='password_reset_complete'),
    path('rules', views.rules, name='rules'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('multiplayer_leaderboard/', views.multiplayer_leaderboard, name='multiplayer_leaderboard'),
    path('not_found', views.not_found, name='not_found'),
    path('quiz_categories/', views.view_quiz_categories, name='quiz_categories'),
    path('quiz_categories/<category>/', views.view_quizzes_by_category, name='quizzes_by_category'),
    path('quiz/<quiz_id>/', views.view_quiz, name='view_quiz'),
    path('quiz/<quiz_id>/single_choice_question/<question_id>/', views.view_single_choice_question, name='view_single_choice_question'),
    path('quiz/<quiz_id>/multiple_choice_question/<question_id>/', views.view_multiple_choice_question, name='view_multiple_choice_question'),
    path('results/<quiz_id>/', views.results, name='results'),
    path('create_edit_page', views.create_edit_page, name='create_edit_page'),
    path('create/', views.create, name='create'),
    path('create_category/', views.create_category, name='create_category'),
    path('create_quiz/', views.create_quiz, name='create_quiz'),
    path('create_question/', views.create_question, name='create_question'),
    path('create_answer/', views.create_answer, name='create_answer'),
    path('edit/', views.edit, name='edit'),
    path('delete_category/<category_id>/', views.delete_category, name='delete_category'),
    path('edit_quiz/<quiz_id>/<category>/', views.edit_quiz, name='edit_quiz'),
    path('edit_question/<question_id>/', views.edit_question, name='edit_question'),
    path('show_all_questions_for_player/', views.show_all_questions_for_player, name='show_all_questions_for_player'),
    path('show_all_answers_for_player/', views.show_all_answers_for_player, name='show_all_answers_for_player'),
    path('show_all_quizzes_for_player/', views.show_all_quizzes_for_player, name='show_all_quizzes_for_player'),
    path('edit_answer/<answer_id>/', views.edit_answer, name='edit_answer'),
    path('forum_page/', views.forum_page, name='forum_page'),
    path('delete_forum_page/<forum_id>/', views.delete_forum_page, name='delete_forum_page'),
    path('add_in_forum/', views.add_in_forum, name='add_in_forum'),
    path('add_in_discussion/', views.add_in_discussion, name='add_in_discussion'),
    path('statistics/', views.view_statistics, name='statistics'),
    path('statistics_for_per_player/', views.view_statistics_for_per_player, name='statistics_for_per_player'),
    path('statistics_for_each_quiz_score/', views.view_statistics_for_each_quiz_score, name='statistics_for_each_quiz_score'),
    path('multiplayer/<room_code>/', views.view_multiplayer, name='multiplayer'),
]